version: '2.4'

x-default: &default
  dns:
    - 8.8.8.8
    - 9.9.9.9

x-mysqlenv:
  - &mysqlUser admin
  - &mysqlPass ${MYSQL_PASSWORD}
  - &mysqlDbName ${MYSQLDUMP_DATABASE}

services:

  # Database for testing.
  db:
    <<: *default
    image: mysql:5.7.37
    ports:
      - 3306
    command: ["mysqld"]
    environment:
      MYSQL_ROOT_PASSWORD: *mysqlPass
      MYSQL_DATABASE: *mysqlDbName
      MYSQL_USER: *mysqlUser
      MYSQL_PASSWORD: *mysqlPass
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping -h localhost       # Use $$ for escaping $
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m
    volumes:
      - mysqldb-data:/var/lib/mysql
    restart: on-failure

  wiki-backup:
    <<: *default
    build:
      context: .
      args:
        # GIT_COMMIT load from .envrc via direnv
        GIT_COMMIT_ID: ${GIT_COMMIT:-unspecified}
    image: tamilwiki/mediawiki_backup_restore:dev
    environment:      
      CRON_TIME_HOURLY: "0 */1 * * *"
      CRON_TIME_DAILY: "0 */24 * * *"
      CRON_TIME_WEEKLY: "0 3 * * SUN"
      CRON_TIME_MONTHLY: "0 4 1 * *"
      S3_LIFECYCLE_EXPIRATION_DAYS_FOR_HOURLY_BACKUP: 1
      S3_LIFECYCLE_EXPIRATION_DAYS_FOR_DAILY_BACKUP: 7
      S3_LIFECYCLE_EXPIRATION_DAYS_FOR_WEEKLY_BACKUP: 365
      S3_LIFECYCLE_EXPIRATION_DAYS_FOR_MONTHLY_BACKUP: 365
      INIT_BACKUP: 1
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      # The content in this env append while restoring the SQL file.
      # Some older MySQL Server needs extra options has to be enabled.
      MYSQL_RESTORE_OPTIONS: ""
      MYSQL_USER: ${MYSQL_USER}
      MYSQLDUMP_DATABASE: ${MYSQLDUMP_DATABASE}
      RESTORE_DATABASE: ${MYSQLDUMP_DATABASE}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PREFIX: ${S3_PREFIX}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    restart: on-failure

volumes:
  mysqldb-data:
