name: Publish Docker image

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfiles:
          - context: .
            dockerfile: ./Dockerfile
            image: tamilwiki/mediawiki_backup_restore            
          - context: ./monitor
            dockerfile: ./monitor/Dockerfile          
            image: tamilwiki/mediawiki_backup_monitor            
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.dockerfiles.image }}
      -
        name: Build and push Docker image for backup
        uses: docker/build-push-action@v2
        with:                        
          file: ${{ matrix.dockerfiles.dockerfile }}
          context: ${{ matrix.dockerfiles.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
